export const REQUEST_USER = "REQUEST_USER";
export const RECIEVE_USER_SUCCESS = "RECIEVE_USER_SUCCESS";
export const RECIEVE_USER_FAILURE = "RECIEVE_USER_FAILURE";


export const ADD_MESSAGE = 'ADD_MESSAGE';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';

export const ADD_FRIEND = 'ADD_FRIEND';
export const CHANGE_FRIEND = 'CHANGE_FRIEND';
export const RECEIVE_FRIEND = 'RECEIVE_FRIEND'; 
export const ADD_USER = 'ADD_USER';

export const REMOVE_USER_FROM_FRIEND = 'REMOVE_USER_FROM_FRIEND';

export const SAVE_USERNAME = 'SAVE_USERNAME';

export const LOAD_MESSAGES = 'LOAD_MESSAGES';
export const LOAD_MESSAGES_SUCCESS = 'LOAD_MESSAGES_SUCCESS';
export const LOAD_MESSAGES_FAIL = 'LOAD_MESSAGES_FAIL';

export const LOAD_FRIENDS = 'LOAD_FRIENDS';
export const LOAD_FRIENDS_SUCCESS  = 'LOAD_FRIENDS_SUCCESS';
export const LOAD_FRIENDS_FAIL = 'LOAD_FRIENDS_FAIL';

export const LOAD_USERSONLINE = 'LOAD_USERSONLINE';
export const LOAD_USERSONLINE_SUCCESS = 'LOAD_USERSONLINE_SUCCESS';
export const LOAD_USERSONLINE_FAIL = 'LOAD_USERSONLINE_FAIL';

export const RECEIVE_USER = 'RECEIVE_USER';

export const START_USERNAME_VALIDATION = 'START_USERNAME_VALIDATION';
export const USERNAME_VALIDATION_SUCCESS = 'USERNAME_VALIDATION_SUCCESS';
export const USERNAME_VALIDATION_FAIL = 'USERNAME_VALIDATION_FAIL';

export const LOAD_USERVALIDATION = 'LOAD_USERVALIDATION';
export const LOAD_USERVALIDATION_SUCCESS = 'LOAD_USERVALIDATION_SUCCESS';
export const LOAD_USERVALIDATION_FAIL = 'LOAD_USERVALIDATION_FAIL';

export const RECEIVE_MESSAGES = 'RECEIVE_MESSAGES';
 
export const RECEIVE_SOCKET = 'RECEIVE_SOCKET';

